"""create trades table

Revision ID: 5b99070d35b3
Revises:
Create Date: 2026-06-11 14:01:30.414750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b99070d35b3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the ``trades`` table, its ``exchange`` enum type, and its indexes.

    Establishes the ``(exchange, trade_id)`` unique constraint the
    application relies on for idempotent inserts, plus non-unique indexes on
    ``symbol`` and ``trade_id``. The ``side`` column arrives in the next
    revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("ts_event", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ts_ingest", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "exchange",
            sa.Enum("BINANCE", "KRAKEN", "COINBASE", name="exchange"),
            nullable=False,
        ),
        sa.Column("trade_id", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange", "trade_id"),
    )
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    op.create_index(op.f("ix_trades_trade_id"), "trades", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the indexes and the ``trades`` table, discarding all stored ticks."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_trade_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades")
    op.drop_table("trades")
    # ### end Alembic commands ###
